name: 'Versioning'
description: 'Automatically bump version of package.json according to description of PR'
inputs:
  current:
    description: 'Current version on master branch'
outputs:
  size:
    description: 'The size of the bump (either major, minor or patch)'
  version:
    description: 'The new version after the bump'
runs:
  using: 'node12'
  main: 'dist/index.js'